# Generated by Django 6.1.2 on 2026-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="nome"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        choices=[
                            ("linux", "Linux"),
                            ("windows", "Windows"),
                            ("other", "Outro"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("prod", "Produção"),
                            ("staging", "Teste"),
                            ("dev", "Desenvolvimento"),
                        ],
                        default="prod",
                        max_length=20,
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="responsável"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token_hash",
                    models.CharField(
                        blank=True, editable=False, max_length=64, unique=True
                    ),
                ),
                (
                    "token_prefix",
                    models.CharField(blank=True, editable=False, max_length=8),
                ),
                (
                    "token_expires_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
