# Generated by Django 6.1.2 on 2026-10-07 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SigningCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="nome"),
                ),
                (
                    "thumbprint",
                    models.CharField(
                        editable=False,
                        max_length=40,
                        unique=True,
                        verbose_name="thumbprint (SHA-1)",
                    ),
                ),
                ("subject", models.CharField(editable=False, max_length=512)),
                ("not_before", models.DateTimeField(editable=False)),
                (
                    "not_after",
                    models.DateTimeField(editable=False, verbose_name="expira em"),
                ),
                (
                    "store_name",
                    models.CharField(default="My", max_length=64, verbose_name="store"),
                ),
                (
                    "machine_store",
                    models.BooleanField(
                        default=True, verbose_name="LocalMachine (senão CurrentUser)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SigningRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField()),
                ("sha256_original", models.CharField(max_length=64)),
                ("sha256_signed", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "Assinado"), ("failed", "Falhou")],
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("via_api", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="signing.signingcertificate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signing_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_sign", "Pode assinar ficheiros")],
            },
        ),
        migrations.CreateModel(
            name="SigningToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="descrição")),
                (
                    "token_hash",
                    models.CharField(editable=False, max_length=64, unique=True),
                ),
                ("token_prefix", models.CharField(editable=False, max_length=8)),
                ("expires_at", models.DateTimeField(editable=False)),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
                (
                    "last_used",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signing_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
